apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: MANUAL_CSR_APPROVAL
          value: "${MANUAL_CSR_APPROVAL:=disable}"
        args:
        - --enable-leader-election
        - "--metrics-bind-addr=127.0.0.1:8080"
        image: docker.io/psarwate/pf9-cluster-api-byoh-controller:dev 
        name: manager
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
