apiVersion: v1
kind: NameSpace
metadata:
 name: byoh
 labels:
  name: byoh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: byoh
---
apiVersion: v1
kind: Secret
metadata:
  name: default-token
  namespace: byoh
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
---
# cat rbac_csr.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: byoh
  name: certificate-manager
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "approve", "issue"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-certificate-manager
  namespace: byoh
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: Role
  name: certificate-manager
  apiGroup: rbac.authorization.k8s.io
---
# cat roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: byoh
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "approve"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-binding
  namespace: byoh
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csr-manager
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "approve", "issue"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csr-manager-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: ClusterRole
  name: csr-manager
  apiGroup: rbac.authorization.k8s.io
---

