apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: byoh
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "approve"]
- apiGroups: ["infrastructure.cluster.x-k8s.io", "infrastructure.cluster.x-k8s.io/v1beta1"]
  resources: ["byohosts", "byohost"]
  verbs: ["create", "update", "get", "list", "watch", "delete", "patch"]
- apiGroups: ["infrastructure.cluster.x-k8s.io", "infrastructure.cluster.x-k8s.io/v1beta1"]
  resources: ["byohosts/status", "byohost/status"]
  verbs: ["patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csr-manager
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "list", "watch", "approve", "issue"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: byo-manager
rules:
- apiGroups: ["infrastructure.cluster.x-k8s.io", "infrastructure.cluster.x-k8s.io/v1beta1"]
  resources: ["byohosts", "byohost"]
  verbs: ["create", "update", "get", "list", "watch", "delete", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
