apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-binding
  namespace: byoh
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csr-manager-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: ClusterRole
  name: csr-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: byohosts-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: byoh
roleRef:
  kind: ClusterRole
  name: byo-manager
  apiGroup: rbac.authorization.k8s.io
