byohImage: quay.io/platform9/cluster-api-provider-bringyourownhost/controller-manager:dev
resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi
byohostAgentHeartbeatTimeout: 120s
