// Copyright 2021 VMware, Inc. All Rights Reserved.
// Copyright 2026 Platform9, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	clusterv1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

const (
	// HostCleanupAnnotation annotation used to mark a host for cleanup
	HostCleanupAnnotation = "byoh.infrastructure.cluster.x-k8s.io/unregistering"
	// EndPointIPAnnotation annotation used to store the IP address of the endpoint
	EndPointIPAnnotation = "byoh.infrastructure.cluster.x-k8s.io/endpointip"
	// K8sVersionAnnotation annotation used to store the k8s version
	K8sVersionAnnotation = "byoh.infrastructure.cluster.x-k8s.io/k8sversion"
	// AttachedByoMachineLabel label used to mark a node name attached to a byo host
	AttachedByoMachineLabel = "byoh.infrastructure.cluster.x-k8s.io/byomachine-name"
	// HostArchitectureLabel mirrors Status.HostDetails.Architecture onto
	// Labels so it is selectable — label selectors cannot match on status
	// fields.
	HostArchitectureLabel = "byoh.infrastructure.cluster.x-k8s.io/architecture"
	// HostOSFamilyLabel reports which package manager this host uses, for
	// selecting an agent-upgrade cohort by package format. Value is one of
	// HostOSFamilyDebian / HostOSFamilyRHEL.
	HostOSFamilyLabel = "byoh.infrastructure.cluster.x-k8s.io/os-family"
	// HostOSFamilyDebian is the HostOSFamilyLabel value for hosts whose
	// package manager is dpkg.
	HostOSFamilyDebian = "debian"
	// HostOSFamilyRHEL is the HostOSFamilyLabel value for hosts whose
	// package manager is rpm.
	HostOSFamilyRHEL = "rhel"
	// BundleLookupBaseRegistryAnnotation annotation used to store the base registry for the bundle lookup
	BundleLookupBaseRegistryAnnotation = "byoh.infrastructure.cluster.x-k8s.io/bundle-registry"
	// ClusterLabel label is used to mark a cluster where it is attached to
	ClusterLabel = "kaapi.pf9.io/cluster-name"
	// ClusterLabelCP label is used to mark a control-plane host attached to a cluster
	ClusterLabelCP = "kaapi.pf9.io/cluster-name-cp"
	// Max k8s label value length
	MaxK8sLabelValueLength = 63
	LabelHashLength        = 8 // Using 8 chars of SHA256 hex
	LabelSeparator         = "-"
	// Max length for the prefix part of the byomachine.namespace.byomachine.name combination
	MaxLabelPrefixLength = MaxK8sLabelValueLength - LabelHashLength - len(LabelSeparator) // 54
)

// ByoHostSpec defines the desired state of ByoHost
type ByoHostSpec struct {
	// BootstrapSecret is an optional reference to a Cluster API Secret
	// for bootstrap purpose
	// +optional
	BootstrapSecret *corev1.ObjectReference `json:"bootstrapSecret,omitempty"`

	// InstallationSecret is an optional reference to InstallationSecret
	// generated by InstallerController for K8s installation
	// +optional
	InstallationSecret *corev1.ObjectReference `json:"installationSecret,omitempty"`

	// UninstallationScript is an optional field to store uninstall script
	// generated by InstallerController
	// +optional
	// UninstallationScript *string `json:"uninstallationScript,omitempty"`
	UninstallationSecret *corev1.ObjectReference `json:"uninstallationSecret,omitempty"`

	// DesiredAgent, when set, drives a managed agent upgrade on this host.
	// The three fields below are always set together by the
	// ByoHostAgentUpgrade rollout controller; nil means no managed upgrade
	// is in progress.
	// +optional
	DesiredAgent *DesiredAgentSpec `json:"desiredAgent,omitempty"`
}

// DesiredAgentSpec is the agent version/package a host should converge on.
type DesiredAgentSpec struct {
	// Version is the agent version this host should be running. The agent
	// compares this against its own version.Get().GitVersion on every
	// reconcile tick and only acts on a mismatch.
	Version string `json:"version"`

	// PackageURL is an OCI image reference — pulled via `imgpkg pull` — for
	// a bundle containing the .deb/.rpm that installs Version. Not
	// templated and does not reference a Secret — an image reference is
	// not sensitive. The agent extracts the bundle, picks the single *.deb
	// or *.rpm inside it matching its own already-known package manager,
	// and installs it; nothing else is executed. Never used to install a
	// version older than the one currently running — that always requires
	// manual (SSH/Ansible) intervention outside this field. Pinning this
	// reference by digest (@sha256:...) rather than a mutable tag is the
	// primary integrity mechanism; see PackageChecksum for a secondary
	// check.
	// +optional
	PackageURL string `json:"packageURL,omitempty"`

	// PackageChecksum, if set, is the expected checksum ("sha256:<hex>") of
	// the specific .deb/.rpm file extracted from the PackageURL bundle —
	// not of the OCI image itself, which digest-pinning the reference
	// above already covers. The agent refuses to install on mismatch.
	// +optional
	PackageChecksum string `json:"packageChecksum,omitempty"`

	// AssignedAt is when the ByoHostAgentUpgrade rollout controller set
	// this field, used to measure elapsed time against
	// ByoHostAgentUpgradeSpec.PerHostTimeout. Only the controller reads or
	// writes it; the agent ignores it.
	// +optional
	AssignedAt metav1.Time `json:"assignedAt,omitempty"`
}

// HostInfo is a set of details about the host platform.
type HostInfo struct {
	// The Operating System reported by the host.
	OSName string `json:"osname,omitempty"`

	// OS Image reported by the host.
	OSImage string `json:"osimage,omitempty"`

	// The Architecture reported by the host.
	Architecture string `json:"architecture,omitempty"`
}

// ByoHostStatus defines the observed state of ByoHost
type ByoHostStatus struct {
	// MachineRef is an optional reference to a Cluster API Machine
	// using this host.
	// +optional
	MachineRef *corev1.ObjectReference `json:"machineRef,omitempty"`

	// Conditions defines current service state of the BYOMachine.
	// +optional
	Conditions clusterv1.Conditions `json:"conditions,omitempty"`

	// HostDetails returns the platform details of the host.
	// +optional
	HostDetails HostInfo `json:"hostinfo,omitempty"`

	// Network returns the network status for each of the host's configured
	// network interfaces.
	// +optional
	Network []NetworkStatus `json:"network,omitempty"`

	// LastHeartbeatTime is the last time the agent running on this host
	// confirmed it was alive. clusterv1.Condition has no per-condition
	// heartbeat/last-probe-time field (unlike corev1.NodeCondition), so this
	// is tracked as a top-level status field rather than as part of the
	// AgentConnected condition below. The management-cluster ByoHostReconciler
	// compares this against its configured HeartbeatTimeoutPeriod to compute
	// AgentConnected; it does not read or write this field itself — only the
	// host agent does.
	// +optional
	LastHeartbeatTime *metav1.Time `json:"lastHeartbeatTime,omitempty"`

	// AgentVersion is the version.GitVersion of the agent binary currently
	// running on this host, as reported by the agent itself. The management
	// cluster only reads it.
	// +optional
	AgentVersion string `json:"agentVersion,omitempty"`

	// MachineID uniquely identifies the underlying machine this host runs on,
	// read from /etc/machine-id (falling back per systemd's machine-id(5)
	// convention where absent) and reported by the agent itself. Unlike the
	// ByoHost name — derived from os.Hostname(), which can change, collide, or
	// be reused across a re-provisioned machine — this does not change unless
	// the machine itself is reimaged. It is a fact, not an enforcement
	// mechanism: this ADR only surfaces it, it does not compare it against
	// anything or reject a mismatch.
	// +optional
	MachineID string `json:"machineID,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:resource:path=byohosts,scope=Namespaced,shortName=byoh
//+kubebuilder:subresource:status
//+kubebuilder:printcolumn:name="OSName",type="string",JSONPath=`.status.hostinfo.osname`
//+kubebuilder:printcolumn:name="OSImage",type="string",JSONPath=`.status.hostinfo.osimage`
//+kubebuilder:printcolumn:name="Arch",type="string",JSONPath=`.status.hostinfo.architecture`

// ByoHost is the Schema for the byohosts API
type ByoHost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ByoHostSpec   `json:"spec,omitempty"`
	Status ByoHostStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// ByoHostList contains a list of ByoHost
type ByoHostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ByoHost `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ByoHost{}, &ByoHostList{})
}

// GetConditions gets the ByoHost status conditions
func (byoHost *ByoHost) GetConditions() clusterv1.Conditions {
	return byoHost.Status.Conditions
}

// SetConditions sets the ByoHost status conditions
func (byoHost *ByoHost) SetConditions(conditions clusterv1.Conditions) {
	byoHost.Status.Conditions = conditions
}
