name: Go version

on:
  workflow_call:
    outputs:
      version:
        description: 'Go version for all CI actions'
        value: ${{ jobs.setup.outputs.version }}

permissions: {}

env:
  GO_VERSION: "1.26.4"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.GO_VERSION }}
    steps:
      - name: Set Go version
        run: echo "Go version is ${{ env.GO_VERSION }}"
