name: golangci-lint

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'
permissions:
  contents: read
jobs:
  golangci:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go 1.24.2
      uses: actions/setup-go@v4
      with:
        go-version: 1.24.2

    - name: Checkout code
      uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64.8
